import { Poppins } from "next/font/google";
import "./globals.css";
import BlockchainProvider from "@/providers/blockchain-provider";
import Header from "@/common-components/globals/header";
import { Toaster } from "sonner";
import "react-circular-progressbar/dist/styles.css";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <BlockchainProvider>
          <Header />
          {children}
          <Toaster theme="dark" />
        </BlockchainProvider>
      </body>
    </html>
  );
}
